#!/usr/bin/env bash
# ============================================================================
# worktree-new.sh <n> [base] — create a native harness worktree for an MVP.
# ----------------------------------------------------------------------------
# Convention DERIVED from the MVP number (nothing to assign by hand):
#   · worktree : ../<repo>-mvp-<n>
#   · branch   : feat/mvp-<n>           (from <base>, default: the current branch)
#   · port     : 3000 + <n>             (mvp-7 -> :3007)  app + e2e baseURL
#   · sandbox  : mvp_<n>                (Lane 1, isolated migration DB)
#
# Leaves ready:
#   · .env.local symlinks (root + apps/web) pointing at the real .env.local
#   · .harness-env with PORT / E2E_BASE_URL / SANDBOX_DB / MVP_N (source it)
#   · roadmap mvp-<n>.json symlinked to the main repo (single source of truth)
#
# Usage:  bash harness/scripts/worktree-new.sh <n> [base]
#         pnpm worktree:new <n>
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR/../.."
MAIN_ROOT="$(git rev-parse --show-toplevel)"
REPO_NAME="$(basename "$MAIN_ROOT")"
ENV_REAL="${MAIN_ROOT}/.env.local"

N="${1:-}"
# Default base: develop if it exists (team convention), else the current branch —
# a fresh scaffold only has main/master.
DEFAULT_BASE="$(git show-ref --verify --quiet refs/heads/develop && echo develop || git branch --show-current)"
BASE="${2:-$DEFAULT_BASE}"

if ! [[ "$N" =~ ^[0-9]+$ ]]; then
  echo "Usage: bash harness/scripts/worktree-new.sh <n> [base]" >&2
  exit 2
fi

BRANCH="feat/mvp-${N}"
DIR="$(dirname "$MAIN_ROOT")/${REPO_NAME}-mvp-${N}"
PORT=$((3000 + N))
SANDBOX_DB="mvp_${N}"

if [ -e "$DIR" ]; then
  echo "x Already exists: $DIR  (use it or remove it: git worktree remove $DIR)" >&2
  exit 1
fi

echo "> Worktree MVP-${N}"
echo "  dir:    $DIR"
echo "  branch: $BRANCH (from $BASE)"
echo "  port:   $PORT   ·   sandbox: $SANDBOX_DB"

# 1) Worktree + branch. Reuse the branch if it exists; otherwise create from <base>.
if git show-ref --verify --quiet "refs/heads/${BRANCH}"; then
  git worktree add "$DIR" "$BRANCH"
else
  git worktree add "$DIR" -b "$BRANCH" "$BASE"
fi

# 2) Env: the real .env.local is gitignored, so a fresh worktree doesn't carry it.
#    Symlink it to reuse the SAME keys without copying secrets.
if [ -f "$ENV_REAL" ]; then
  ln -sfn "$ENV_REAL" "$DIR/.env.local"
  ln -sfn "../../.env.local" "$DIR/apps/web/.env.local"
  echo "  · .env.local symlinked (root + apps/web)"
else
  echo "  ! No .env.local in the main repo; create it and re-symlink by hand."
fi

# 2b) Roadmap: mvp-<n>.json are gitignored working files. Symlink THIS MVP's file
#     to the main repo so the worktree session reads/updates the SAME roadmap.
ROADMAP_REL="harness/docs/roadmap/mvp-${N}.json"
if [ -f "$MAIN_ROOT/$ROADMAP_REL" ]; then
  ln -sfn "$MAIN_ROOT/$ROADMAP_REL" "$DIR/$ROADMAP_REL"
  echo "  · roadmap mvp-${N}.json symlinked to the main repo"
fi

# 3) Worktree runtime manifest. Source it once per terminal:
#       cd $DIR && source .harness-env
cat > "$DIR/.harness-env" <<EOF
# Generated by worktree-new.sh — runtime for this worktree (MVP-${N}).
# Source it in every worktree terminal:  source .harness-env
export MVP_N=${N}
export PORT=${PORT}
export E2E_BASE_URL="http://localhost:${PORT}"
export SANDBOX_DB=${SANDBOX_DB}
EOF
echo "  · .harness-env written (MVP_N/PORT/E2E_BASE_URL/SANDBOX_DB)"

cat <<EOF

OK Worktree MVP-${N} ready.
  cd ${DIR}
  source .harness-env          # loads PORT=${PORT} in this terminal
  pnpm install                 # (if needed) worktree deps
  pnpm dev                     # app on :${PORT}
  pnpm e2e:local               # full e2e, serialized by lock (Lane 2)
EOF
